name: Trigger auto deployment for container-app-exyvgnjht7w5y

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-exyvgnjht7w5y-AutoDeployTrigger-feebf429-4ca6-4a08-92fc-e428632c4a42.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPEXYVGNJHT7W5Y_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPEXYVGNJHT7W5Y_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPEXYVGNJHT7W5Y_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryexyvgnjht7w5y.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPEXYVGNJHT7W5Y_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPEXYVGNJHT7W5Y_REGISTRY_PASSWORD }}
          containerAppName: container-app-exyvgnjht7w5y
          resourceGroup: expresssamplebd97ac83
          imageToBuild: containerregistryexyvgnjht7w5y.azurecr.io/container-app-exyvgnjht7w5y:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


